apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
spec:
  selector:
    matchLabels:
      app: warehouse
  replicas: 1
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      containers:
      - name: warehouse
        image: localhost:5252/warehouse
